In [3]:
import pandas as pd

In [9]:
# Read the text file
df = pd.read_csv('SMSSpamCollection.txt', delimiter='\t', names=['label','message'])

# Display the DataFrame
print(df)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [10]:
# Data Cleaning and preprocessing

import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/jasper/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Using PorterStemmer on smsclassifier csv file

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
porterstemmer = PorterStemmer()

In [13]:
corpus = []
for i in range (0,len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review = review.split()
    review = [porterstemmer.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [14]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
# For binary BagofWords enable binary=True
cv = CountVectorizer(max_features=2500, binary=True)


In [20]:
X = cv.fit_transform(corpus)

In [21]:
X.shape

(5572, 2500)

In [22]:
cv.get_feature_names_out()

array(['aah', 'aathi', 'abi', ..., 'yup', 'zed', 'zoe'], dtype=object)

In [24]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# N Grams

In [26]:
cv.vocabulary_

{'go': np.int64(871),
 'point': np.int64(1602),
 'crazi': np.int64(478),
 'avail': np.int64(153),
 'bugi': np.int64(300),
 'great': np.int64(895),
 'world': np.int64(2434),
 'la': np.int64(1157),
 'cine': np.int64(391),
 'got': np.int64(886),
 'wat': np.int64(2359),
 'ok': np.int64(1497),
 'lar': np.int64(1169),
 'joke': np.int64(1098),
 'wif': np.int64(2402),
 'oni': np.int64(1505),
 'free': np.int64(810),
 'entri': np.int64(683),
 'wkli': np.int64(2423),
 'comp': np.int64(425),
 'win': np.int64(2406),
 'cup': np.int64(492),
 'final': np.int64(767),
 'tkt': np.int64(2194),
 'st': np.int64(2033),
 'may': np.int64(1309),
 'text': np.int64(2148),
 'receiv': np.int64(1731),
 'question': np.int64(1694),
 'std': np.int64(2044),
 'txt': np.int64(2257),
 'rate': np.int64(1712),
 'appli': np.int64(110),
 'dun': np.int64(628),
 'say': np.int64(1835),
 'earli': np.int64(634),
 'alreadi': np.int64(67),
 'nah': np.int64(1423),
 'think': np.int64(2162),
 'goe': np.int64(874),
 'usf': np.int64(2305)

In [ ]:
# Create Bag of Words model with n-grams

from sklearn.feature_extraction.text import CountVectorizer
# For binary BagofWords enable binary=True
# cv = CountVectorizer(max_features=2500, binary=True)
# Unigrams and bi-grams
cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray()


In [29]:
cv.vocabulary_

{'go': np.int64(802),
 'point': np.int64(1615),
 'crazi': np.int64(451),
 'avail': np.int64(122),
 'bugi': np.int64(229),
 'great': np.int64(860),
 'world': np.int64(2428),
 'la': np.int64(1083),
 'cine': np.int64(339),
 'got': np.int64(848),
 'wat': np.int64(2336),
 'ok': np.int64(1478),
 'lar': np.int64(1093),
 'joke': np.int64(1054),
 'wif': np.int64(2393),
 'free': np.int64(716),
 'entri': np.int64(614),
 'wkli': np.int64(2417),
 'comp': np.int64(395),
 'win': np.int64(2398),
 'cup': np.int64(466),
 'final': np.int64(678),
 'st': np.int64(1975),
 'may': np.int64(1265),
 'text': np.int64(2077),
 'receiv': np.int64(1701),
 'question': np.int64(1669),
 'std': np.int64(1988),
 'txt': np.int64(2196),
 'rate': np.int64(1681),
 'appli': np.int64(86),
 'free entri': np.int64(723),
 'entri wkli': np.int64(616),
 'std txt': np.int64(1989),
 'txt rate': np.int64(2204),
 'rate appli': np.int64(1682),
 'dun': np.int64(579),
 'say': np.int64(1798),
 'earli': np.int64(585),
 'alreadi': np.int64(5

In [31]:
# Create Bag of Words model with n-grams

from sklearn.feature_extraction.text import CountVectorizer
# For binary BagofWords enable binary=True
# cv = CountVectorizer(max_features=2500, binary=True)
# Bi-grams
cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()


In [32]:
cv.vocabulary_

{'ok lar': np.int64(1459),
 'free entri': np.int64(641),
 'entri wkli': np.int64(552),
 'wkli comp': np.int64(2426),
 'cup final': np.int64(417),
 'std txt': np.int64(1933),
 'txt rate': np.int64(2193),
 'rate appli': np.int64(1656),
 'freemsg hey': np.int64(660),
 'like fun': np.int64(1128),
 'treat like': np.int64(2138),
 'per request': np.int64(1531),
 'request mell': np.int64(1722),
 'mell mell': np.int64(1260),
 'mell oru': np.int64(1261),
 'oru minnaminungint': np.int64(1492),
 'minnaminungint nurungu': np.int64(1289),
 'nurungu vettam': np.int64(1438),
 'vettam set': np.int64(2288),
 'set callertun': np.int64(1821),
 'callertun caller': np.int64(206),
 'caller press': np.int64(204),
 'press copi': np.int64(1622),
 'copi friend': np.int64(389),
 'friend callertun': np.int64(663),
 'winner valu': np.int64(2414),
 'valu network': np.int64(2286),
 'network custom': np.int64(1391),
 'reward claim': np.int64(1735),
 'claim call': np.int64(266),
 'call claim': np.int64(159),
 'claim co

In [ ]:
# Create Bag of Words model with n-grams

from sklearn.feature_extraction.text import CountVectorizer
# For binary BagofWords enable binary=True
# cv = CountVectorizer(max_features=2500, binary=True)
# Tri-grams
cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(3,3))
X = cv.fit_transform(corpus).toarray()

In [34]:
cv.vocabulary_

{'free entri wkli': np.int64(752),
 'entri wkli comp': np.int64(657),
 'fa cup final': np.int64(706),
 'cup final tkt': np.int64(446),
 'st may text': np.int64(1908),
 'text fa receiv': np.int64(2051),
 'fa receiv entri': np.int64(707),
 'receiv entri question': np.int64(1715),
 'entri question std': np.int64(652),
 'std txt rate': np.int64(1930),
 'txt rate appli': np.int64(2217),
 'per request mell': np.int64(1499),
 'request mell mell': np.int64(1753),
 'mell mell oru': np.int64(1259),
 'mell oru minnaminungint': np.int64(1260),
 'oru minnaminungint nurungu': np.int64(1477),
 'minnaminungint nurungu vettam': np.int64(1299),
 'nurungu vettam set': np.int64(1425),
 'vettam set callertun': np.int64(2370),
 'set callertun caller': np.int64(1841),
 'callertun caller press': np.int64(210),
 'caller press copi': np.int64(207),
 'press copi friend': np.int64(1643),
 'copi friend callertun': np.int64(409),
 'winner valu network': np.int64(2446),
 'valu network custom': np.int64(2361),
 'cust

In [35]:
# Create Bag of Words model with n-grams

from sklearn.feature_extraction.text import CountVectorizer
# For binary BagofWords enable binary=True
# cv = CountVectorizer(max_features=2500, binary=True)
# Bi-grams and tri-grams
cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(2,3))
X = cv.fit_transform(corpus).toarray()


In [36]:
cv.vocabulary_

{'ok lar': np.int64(1418),
 'free entri': np.int64(641),
 'entri wkli': np.int64(542),
 'wkli comp': np.int64(2440),
 'cup final': np.int64(445),
 'std txt': np.int64(1906),
 'txt rate': np.int64(2132),
 'rate appli': np.int64(1612),
 'free entri wkli': np.int64(643),
 'std txt rate': np.int64(1907),
 'txt rate appli': np.int64(2133),
 'like fun': np.int64(1063),
 'per request': np.int64(1490),
 'request mell': np.int64(1682),
 'oru minnaminungint': np.int64(1460),
 'nurungu vettam': np.int64(1393),
 'vettam set': np.int64(2268),
 'set callertun': np.int64(1782),
 'callertun caller': np.int64(226),
 'caller press': np.int64(221),
 'press copi': np.int64(1577),
 'copi friend': np.int64(408),
 'friend callertun': np.int64(665),
 'per request mell': np.int64(1491),
 'request mell mell': np.int64(1683),
 'oru minnaminungint nurungu': np.int64(1461),
 'nurungu vettam set': np.int64(1394),
 'vettam set callertun': np.int64(2269),
 'set callertun caller': np.int64(1783),
 'callertun caller pr

# TD-IDF